server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  jwt:
    secret: mySuperSecretKey12345678901234567890123456789012
    expiration: 86400000 # 24 horas en milisegundos

admin:
  email: administrator@admin.com
  fullname: Administrador
  password: Admin1234


