spring:
  application:
    name: auth-service
  profiles:
    active: dev
  flyway:
    enabled: false
  jpa:
    open-in-view: false
    show-sql: true

server:
  port: 8081

security:
  jwt:
    secret: very-secret-key-very-secret-key-very-secret
    expiration: 3600000