spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cart_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true

  security:
    jwt:
      secret: very-secret-key-very-secret-key-very-secret
