spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cart_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true

  security:
    jwt:
      secret: mySuperSecretKey12345678901234567890123456789012
      expiration: 86400000 # 24 horas en milisegundos
