spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cart_db
    username: postgresPassword
    password: postgresPassword

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
